config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  # 顧客用
  # URL /customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  get '/customers/my_page' => 'public/customers#show'
  get '/customers/infomation/edit' => 'public/customers#edit'
  patch '/customers/infomation' => 'public/customers#update'
  get '/customers/current_customer/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        get 'thanks'
        post 'confirm'
      end
    end
    # get '/orders/thanks' => 'orders#thanks'
    # post '/orders/confirm' => 'orders#confirm'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  get '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all'


  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get '/admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy #中間テーブル
  has_many :orders, through: :order_items

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_yoko.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price # 税込価格
    (price * 1.1).floor
  end
  
  # def count #全件
  #   Item.count
  # end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-5 bg-light d-inline">商品編集</h4>
  </div>

  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td><%= f.label :image, "商品画像" %></td>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <td><%= f.label :name, "商品名" %></td>
              <td><%= f.text_field :name, size: 40 %></td>
            </tr>
            <tr>
              <td><%= f.label :introduction, "商品説明" %></td>
              <td><%= f.text_area :introduction, size: "40x10" %></td>
            </tr>
            <tr>
              <td><%= f.label :price, "税抜価格" %></td>
              <td><%= f.text_field :price, size: 40 %>円</td>
            </tr>
          </tbody>
        </table>
        <%= f.submit "変更を保存", class: "btn btn-success mt-5 mx-auto" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h4 class="my-5 bg-light d-inline">商品一覧</h4>
    </div>
    <div class="col-md-2">
      <%= link_to "+", new_admin_item_path, class: "shadow-sm btn rounded-circle" %>
    </div>
  </div>

  <div class="row mt-3">
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">商品ID</th>
          <th scope="col">商品名</th>
          <th scope="col">税抜価格</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id), class: "link-dark" %></td>
          <td><%= item.price.to_s(:delimited) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-5 bg-light d-inline">商品新規登録</h4>
  </div>

  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td><%= f.label :image, "商品画像" %></td>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <td><%= f.label :"商品名" %></td>
              <td><%= f.text_field :name, :placeholder => "商品名", size: 40 %></td>
            </tr>
            <tr>
              <td><%= f.label :"商品説明" %></td>
              <td><%= f.text_area :introduction, :placeholder => "ここに説明文を記述します", size: "40x10" %></td>
            </tr>
            <tr>
              <td><%= f.label :"税抜価格" %></td>
              <td><%= f.text_field :price, :placeholder => "1000", size: 40 %>円</td>
            </tr>
          </tbody>
        </table>
        <%= f.submit "新規登録", class: "btn btn-success mt-5 mx-auto" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-5 bg-light d-inline">商品詳細</h4>
  </div>

  <div class="row mt-5">
    <div class="col-md-4">
      <%= image_tag @item.get_image(200, 300) %>
    </div>
    <div class="col-md-8">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>
              税込価格<br>（税抜価格）
            </td>
            <td>
              <%= @item.add_tax_price.to_s(:delimited) %>
              (<%= @item.price.to_s(:delimited) %>)円
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto mt-5">
      <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
    </div>
  </div>
</div>