config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  # 顧客用
  # URL /customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  get '/customers/my_page' => 'public/customers#show'
  get '/customers/infomation/edit' => 'public/customers#edit'
  patch '/customers/infomation' => 'public/customers#update'
  get '/customers/current_customer/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        get 'thanks'
        post 'confirm'
      end
    end
    # get '/orders/thanks' => 'orders#thanks'
    # post '/orders/confirm' => 'orders#confirm'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  get '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all'


  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get '/admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-5 bg-light d-inline">
      <%= @customer.last_name + @customer.first_name + "さんの会員詳細編集"%>
    </h4>
  </div>

  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <td>氏名</td>
              <td>
                <%= f.text_field :last_name %>
                <%= f.text_field :first_name %>
              </td>
            </tr>
            <tr>
              <td>フリガナ</td>
              <td>
                <%= f.text_field :last_name_kana %>
                <%= f.text_field :first_name_kana %>
              </td>
            </tr>
            <tr>
              <td>郵便番号</td>
              <td><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td><%= f.text_field :address, size: 60 %></td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td><%= f.text_field :telephone_number %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
            </tr>
            <tr>
              <td>会員ステータス</td>
              <td>
                <%= f.radio_button :is_deleted, 'false' %>
                <%= f.label :is_deleted, "有効" %>

                <%= f.radio_button :is_deleted, 'true' %>
                <%= f.label :is_deleted, "退会" %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-5 bg-light d-inline">会員一覧</h4>
  </div>

  <div class="row mt-1">
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">会員ID</th>
          <th scope="col">氏名</th>
          <th scope="col">メールアドレス</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == false %>
              <p class="text-success">有効</p>
            <% else %>
              <p class="text-muted">退会</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-5 bg-light d-inline">
      <%= @customer.last_name + @customer.first_name + "さんの会員詳細"%>
    </h4>
  </div>

  <div class="row">
    <div>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name + "" + @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana + "" + @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @customer.is_deleted == false %>
                <p class="text-success">有効</p>
              <% else %>
                <p class="text-muted">退会</p>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto mt-3">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary ml-5" %>
    </div>
  </div>
</div>