config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  # 顧客用
  # URL /customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  get '/customers/my_page' => 'public/customers#show'
  get '/customers/infomation/edit' => 'public/customers#edit'
  patch '/customers/infomation' => 'public/customers#update'
  get '/customers/current_customer/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        get 'thanks'
        post 'confirm'
      end
    end
    # get '/orders/thanks' => 'orders#thanks'
    # post '/orders/confirm' => 'orders#confirm'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  get '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all'


  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get '/admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit: 0, #クレジットカード
    bank: 1, #銀行振込
  }

  has_many :order_items, dependent: :destroy #中間テーブル
  has_many :items, through: :order_items
  belongs_to :customer #親モデル

  def item_total
    # order_itemのsubtotalの合計
    total = 0
    order_items.each do |order_item|
      total += order_item.subtotal
    end
    return total
  end

  def amount_total
    total = 0
    order_items.each do |order_item|
      total += order_item.amount
    end
    return total
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @customer = @order.customer
  end

  # private

  # # def order_params
  # #   params.require(:order).permit(:postal_code, :address, :address_name, :payment_method, :postage, :total_payment)
  # # end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-5 bg-light d-inline">注文履歴詳細</h4>
  </div>

  <div class="row">
    <div>
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td><%= link_to @customer.last_name + @customer.first_name, admin_customer_path(@customer.id) %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%-m/%-d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            〒<%= @order.postal_code %>
              <%= @order.address %><br>
              <%= @order.address_name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
      </table>
    </div>
    <div class="row">
      <div class="col-md-8">
        <table class="table table-borderless">
          <thead class="table-secondary">
            <th scope="col">商品名</th>
            <th scope="col">単価(税込)</th>
            <th scope="col">数量</th>
            <th scope="col">小計</th>
          </thead>
          <tbody>
            <% @order_items.each do |order_item| %>
                <tr>
                  <td><%= order_item.item.name %></td>
                  <td><%= order_item.purchase_price.to_s(:delimited) %></td>
                  <td><%= order_item.amount %></td>
                  <td><%= order_item.subtotal.to_s(:delimited) %></td>
                </tr>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class="col-md-4">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= @order.item_total.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><strong><%= @order.total_payment.to_s(:delimited) %></strong></td>
        </tr>
      </table>
    </div>
  </div>
</div>