config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  # 顧客用
  # URL /customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  get '/customers/my_page' => 'public/customers#show'
  get '/customers/infomation/edit' => 'public/customers#edit'
  patch '/customers/infomation' => 'public/customers#update'
  get '/customers/current_customer/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create] do
      collection do
        get 'thanks'
        post 'confirm'
      end
    end
    # get '/orders/thanks' => 'orders#thanks'
    # post '/orders/confirm' => 'orders#confirm'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  get '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all'


  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get '/admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer #親モデル
  belongs_to :item #親モデル
  
  def subtotal # 小計
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy #中間テーブル
  has_many :orders, through: :order_items

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_yoko.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price # 税込価格
    (price * 1.1).floor
  end
  
  # def count #全件
  #   Item.count
  # end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit: 0, #クレジットカード
    bank: 1, #銀行振込
  }

  has_many :order_items, dependent: :destroy #中間テーブル
  has_many :items, through: :order_items
  belongs_to :customer #親モデル

  def item_total
    # order_itemのsubtotalの合計
    total = 0
    order_items.each do |order_item|
      total += order_item.subtotal
    end
    return total
  end

  def amount_total
    total = 0
    order_items.each do |order_item|
      total += order_item.amount
    end
    return total
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    purchase_price * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
    # @order_items = @orders.order_items
    # @customer = @orders.customer
  end

  # private

  # def order_params
  #   params.require(:order).permit(:postal_code, :address, :address_name, :payment_method, :postage, :total_payment)
  # end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @customer = @order.customer
  end

  # private

  # # def order_params
  # #   params.require(:order).permit(:postal_code, :address, :address_name, :payment_method, :postage, :total_payment)
  # # end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      admin_path
    end

    def after_sign_out_path_for(resource)
      new_admin_session_path
    end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/aa8c5f352f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navber navbar-expand-sm navbar-light bg-light">
        <div class="container">
          <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3">
          <%= link_to "ながのCAKE", root_path, class: "navbar-brand my-0 mr-md-auto btn btn-outline-secondary" %>

            <ul class="navbar-nav ml-auto">
              <!--管理者サインイン後-->
              <% if admin_signed_in? %>
              <li class="nav-item p-2">
                <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "注文履歴一覧", admin_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
              </li>

              <!--ユーザーサインイン後-->
              <% elsif customer_signed_in? %>
              ようこそ、<%= current_customer.last_name %>さん！
              <li class="nav-item p-2">
                <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary" %>
              </li>

              <!--サインイン前-->
              <% else %>
              <li class="nav-item p-2">
                <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary" %>
              </li>
              <li class="nav-item p-2">
                <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary" %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>